### ISSUE TITLE
Plugin broken with Keen Warfare 1 update

### ISSUE THREAD

**Issue by Blaylock1988** [emawind84/lightning-manager-torch-plugin#1]
The plugin causes a fatal error in torch upon launching torch. No longer usable. We really need this plugin to stop lightning damage without modifying weather for multiple planets.

**Comment by emawind84** [comment]
> The plugin causes a fatal error in torch upon launching torch. No longer usable. We really need this plugin to stop lightning damage without modifying weather for multiple planets.

I will see what I can do

**Comment by emawind84** [comment]
It should be fixed, new version 1.0.1
https://torchapi.net/plugins/item/54e2fcc2-a16b-4361-a95d-e4d16732198b
